### ISSUE TITLE
Bug 17616 - Anomaly with contrast functions

### ISSUE THREAD

**Issue by hturner** [r-devel/bug-bbq#1]
View bug on Bugzilla (reference only): https://bugs.r-project.org/show_bug.cgi?id=17616

**Comment by hturner** [comment]
There are actually two issues here. 

The first is the original one reported by Peter Dalgaard. It boils down to different behaviour of `contrasts<-` when using the name of a contrasts function as a character string vs using the actual function:

``` r
contrasts(CO2$Treatment) <- "contr.treatment"
contrasts(CO2$Treatment)
#>            chilled
#> nonchilled       0
#> chilled          1
contrasts(CO2$Treatment) <- `contr.treatment`
contrasts(CO2$Treatment)
#>            2
#> nonchilled 0
#> chilled    1
```

<sup>Created on 2022-06-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This can be fixed by changing `if(is.function(value)) value <- value(nlevels(x))` on line 53 of `src/library/stats/contrast.R` to `if(is.function(value)) value <- value(levels(x))`. As far as I can see, this should not break anything, because `?contrasts` says

> Suitable [contrast] functions have a first argument which is the character vector of levels, 

I think this should also be fixed in the `C()` function for the case where the `how.many` argument is not missing. E.g.

``` r
contr.treatment(levels(esoph$alcgp))
#>           40-79 80-119 120+
#> 0-39g/day     0      0    0
#> 40-79         1      0    0
#> 80-119        0      1    0
#> 120+          0      0    1
attr(C(esoph$alcgp, "contr.treatment", how.many = 2), "contrasts")
#>           2 3
#> 0-39g/day 0 0
#> 40-79     1 0
#> 80-119    0 1
#> 120+      0 0
```

<sup>Created on 2022-06-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

It is basically the same fix: replace `contr <- contr(nlevels(object), ...)` with `contr <- contr(levels(object), ...)` on line 45 of `C.R`.

The second issue is not a bug, but a mistake by Long Qu in how they defined their contrasts function. As in the quote from `?contrasts` above, the first argument should be able to take the character vector of levels as the first argument. If we correct their custom function (borrowing the initial code from `contr.treatment()`), everything works as it should.

``` r
my.contrast <- function(n, contrasts = TRUE){
    if (is.numeric(n) && length(n) == 1L) {
        if (n > 1L)
            levels <- as.character(seq_len(n))
        else stop("not enough degrees of freedom to define contrasts")
    }
    else {
        levels <- as.character(n)
        n <- length(n)
    }
    a=diag(1,n,n)
    if(!contrasts) return(a)
    a[lower.tri(a)]=1
    a[,-1,drop=FALSE]
}
my.contrast(4)
#>      [,1] [,2] [,3]
#> [1,]    0    0    0
#> [2,]    1    0    0
#> [3,]    1    1    0
#> [4,]    1    1    1

(of=ordered(rep(2:4,2:4)))
#> [1] 2 2 3 3 3 4 4 4 4
#> Levels: 2 < 3 < 4

model.matrix(~of, contrasts.arg=list(of=`my.contrast`))
#>   (Intercept) of1 of2
#> 1           1   0   0
#> 2           1   0   0
#> 3           1   1   0
#> 4           1   1   0
#> 5           1   1   0
#> 6           1   1   1
#> 7           1   1   1
#> 8           1   1   1
#> 9           1   1   1
#> attr(,"assign")
#> [1] 0 1 1
#> attr(,"contrasts")
#> attr(,"contrasts")$of
#>   [,1] [,2]
#> 2    0    0
#> 3    1    0
#> 4    1    1

model.matrix(~of, contrasts.arg=list(of="my.contrast"))
#>   (Intercept) of1 of2
#> 1           1   0   0
#> 2           1   0   0
#> 3           1   1   0
#> 4           1   1   0
#> 5           1   1   0
#> 6           1   1   1
#> 7           1   1   1
#> 8           1   1   1
#> 9           1   1   1
#> attr(,"assign")
#> [1] 0 1 1
#> attr(,"contrasts")
#> attr(,"contrasts")$of
#> [1] "my.contrast"

model.matrix(~C(of, "my.contrast"))
#>   (Intercept) C(of, "my.contrast")1 C(of, "my.contrast")2
#> 1           1                     0                     0
#> 2           1                     0                     0
#> 3           1                     1                     0
#> 4           1                     1                     0
#> 5           1                     1                     0
#> 6           1                     1                     1
#> 7           1                     1                     1
#> 8           1                     1                     1
#> 9           1                     1                     1
#> attr(,"assign")
#> [1] 0 1 1
#> attr(,"contrasts")
#> attr(,"contrasts")$`C(of, "my.contrast")`
#> [1] "my.contrast"

contrasts(of)="my.contrast"
model.matrix(~of)
#>   (Intercept) of1 of2
#> 1           1   0   0
#> 2           1   0   0
#> 3           1   1   0
#> 4           1   1   0
#> 5           1   1   0
#> 6           1   1   1
#> 7           1   1   1
#> 8           1   1   1
#> 9           1   1   1
#> attr(,"assign")
#> [1] 0 1 1
#> attr(,"contrasts")
#> attr(,"contrasts")$of
#> [1] "my.contrast"
```

<sup>Created on 2022-06-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by martynplummer** [comment]
I confirm that the problem with model.matrix reported by Long Qu go away when the contrast function accepts a vector of level names, as the documentation requires (Also seen in ?contr.treatment). I think we can report back in R bugzilla that we have looked at it in the bug BBQ and this part is not an R bug.

**Comment by martynplummer** [comment]
I confirm the two fixes. I have this ready to commit in my local copy of R-devel. But time is getting on so I will do this tomorrow.

**Comment by hturner** [comment]
Thanks Martyn. I'll close this as far as the Bug BBQ goes then.
