### ISSUE TITLE
New issue:  use rgl instead of xgobi in col2rgb example

### ISSUE THREAD

**Issue by dmurdoch** [r-devel/bug-bbq#24]
Here's some code to do a plot like the original, using the `rgl` package.  I've also changed `require()` to `requireNamespace()`, but haven't added `rgl` to the `Suggests:` list.  

This is the resulting plot:

![Screen Shot 2022-06-24 at 12 56 04 PM](https://user-images.githubusercontent.com/1935680/175607509-c646eb8a-37e8-4049-ac6a-4a664ed0b90b.png)

And here is the patch file:

```
Index: src/library/grDevices/man/col2rgb.Rd
===================================================================
--- src/library/grDevices/man/col2rgb.Rd	(revision 82502)
+++ src/library/grDevices/man/col2rgb.Rd	(working copy)
@@ -81,12 +81,13 @@
 names(cl) <- apply(col2rgb(sapply(cl, function(x)x[1])),
                    2, function(n)paste(n, collapse = ","))
 utils::str(cl)
-\dontrun{
- if(require(xgobi)) { ## Look at the color cube dynamically :
-   tc <- t(crgb[, !duplicated(ccodes)])
-   table(is.gray <- tc[,1] == tc[,2] & tc[,2] == tc[,3])  # (397, 105)
-   xgobi(tc, color = c("gold", "gray")[1 + is.gray])
- }
+
+if(requireNamespace("rgl")) { ## Look at the color cube dynamically :
+    tc <- t(crgb[, !duplicated(ccodes)])
+    table(is.gray <- tc[,1] == tc[,2] & tc[,2] == tc[,3])  # (397, 105)
+    rgl::open3d()
+    rgl::bg3d("midnightblue")
+    rgl::points3d(tc, col = c("gold", "gray")[1 + is.gray])
 }
 }
 \keyword{color}
```

**Comment by mmaechler** [comment]
Nice!   You found the magic,  Heather and I did not find quickly:  `bg3d()`
 NB:  This has already been opened in #23

**Comment by dmurdoch** [comment]
Is there a way to merge the two issues?

**Comment by dmurdoch** [comment]
Just thought of something:  should have `rgl::open3d()` before the `rgl::bg3d()` call, or this would appear in an existing `rgl` window.

**Comment by hturner** [comment]
Thanks Duncan. Since @mmaechler referenced the other issue, there is already a link there, so no need to worry about merging.

**Comment by bastistician** [comment]
We could actually use the colors in the color cube.
What about:

```R
###
crgb <- col2rgb(cc <- colors())
colnames(crgb) <- cc
ccodes <- c(256^(2:0) %*% crgb)  # = internal codes
tc <- t(crgb[, !duplicated(ccodes)])
###

if(requireNamespace("lattice", quietly = TRUE))
    lattice::cloud(blue ~ red + green, data = as.data.frame(tc),
                   col = rownames(tc))

## Not run:
## rotatable version (needs the rgl package)
rgl::plot3d(tc, col = rownames(tc))
## End(Not run)
```

![colorcube](https://user-images.githubusercontent.com/4366501/177514727-46865934-4d77-49f0-9bc4-0f53aaf59ee3.png)

I think it would be useful to include a static lattice plot as that is usually available, and then show a potential rgl call.

**Comment by hturner** [comment]
@mmaechler since committed a fix for this in R-devel: https://github.com/r-devel/r-svn/commit/fdc114c2bf965872f039a9e1f5a0aae9984ec9d5
