### ISSUE TITLE
Bug 18367 - `x[[]]` on a vector with an empty string name will select that name

### ISSUE THREAD

**Issue by DavisVaughan** [r-devel/bug-bbq#6]
https://bugs.r-project.org/show_bug.cgi?id=18367

I hope you don't mind that I've added my own bug report here. I was planning on potentially working on it with some other RStudio folk over the Bug BBQ Session 3 if an R Core member were to confirm that it was a bug.

**Comment by BrianDiggs** [comment]
This issue happens with lists as well. I didn't see that example.

```r
x <- list("a" = 1, 2, "c" = 3)
x[[]] # gives "2", incorrectly
x[[""]] # gives NULL (correctly?)
x[[]] <- 4 # gives Error with missing subscript
```

The error message with list assignment is more informative

```r
> x[[]] <- 4
Error in x[[]] <- 4 : [[ ]] with missing subscript
> tryCatch(x[[]]<-4, error = function(e) {str(e)})
List of 2
 $ message: chr "[[ ]] with missing subscript"
 $ call   : language x[[]] <- 4
 - attr(*, "class")= chr [1:3] "simpleError" "error" "condition"
```

**Comment by DavisVaughan** [comment]
I _think_ the list code path for `x[[]]` is the same as the code path for atomic vectors

The error message with list subassignment and with atomic vector subassignment is definitely more informative.

I've updated my bugzilla report with the additional error cases we came up with during the Bug BBQ, and also mentioned that there is some question about exactly what kind of error should be thrown here (i.e. should it be an out of bounds error, or simply an error about using a missing subscript)
https://bugs.r-project.org/show_bug.cgi?id=18367#c6

**Comment by hturner** [comment]
Discussion of this issue has continued on Bugzilla following the Bug BBQ (bug currently closed, but may reopen to fix borderline cases). So will close here.
