### ISSUE TITLE
Bug 18362 - `head(letters, 1:2)` should give better error message 

### ISSUE THREAD

**Issue by mmaechler** [r-devel/bug-bbq#9]
A new one, opened by myself: Not too much work I think; but advanced insofar as you need to be willing to delve into understanding (to some extent)  `errorCondition()` objects:
https://bugs.r-project.org/show_bug.cgi?id=18362

**Comment by gmbecker** [comment]
I believe @ColinFay stated elsewhere he intends to work on this one. Colin please let me know if you'd to work together on this, or alternatively if it turns out you will not end up having the time, as I am happy to help on this one as well.

**Comment by ColinFay** [comment]
Hey @gmbecker,

Yes, I'd love to work on this one :)

happy to collaborate with you if you want to. 
I'll draft something this week and will let you know

**Comment by gmbecker** [comment]
Sounds good I'll leave it to you to be the point-person on this. Let me know when you have something you'd like some more eyes on.

**Comment by hturner** [comment]
Now fixed by @eliocamp
